import {
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Heading1,
  Heading2,
  List,
  ListOrdered,
  Quote,
  Code,
  Undo,
  Redo,
  ListTodo,
  Minus,
} from 'lucide-react';

export const editorIcons = {
  bold: <Bold />,
  italic: <Italic />,
  strike: <Strikethrough />,
  h1: <Heading1 />,
  h2: <Heading2 />,
  bulletList: <List />,
  orderedList: <ListOrdered />,
  todoList: <ListTodo />,
  blockquote: <Quote />,
  codeBlock: <Code />,
  horizontalRule: <Minus />,
  undo: <Undo />,
  redo: <Redo />,
  underline: <Underline />,
};
